name: Update lineages

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - 'MPX/**'
      - 'MEASLESgenome/**'

jobs:
  update_lineages:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        dataset: [MPX, MEASLESgenome]

    defaults:
      run:
        shell: bash -el {0}

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Build lineage hierarchy
        run: |
          pip install pandas==2.2.2 pyyaml==6.0.2

          cd ${{ matrix.dataset }} && python make_hierarchy.py

          # get newest folder
          date=$(ls -td -- */ | head -n 1 | cut -d'/' -f1)

          # copy if missing
          if [ ! -f "$date/lineages.yml" ]; then
            cp lineages.yml $date
          fi

          cp lineages.yml latest && rm lineages.yml

      - name: Commit and push
        run: |
          git pull origin main
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"
          git add ${{ matrix.dataset }}
          git commit -m "Update ${{ matrix.dataset }} lineages" || echo "No changes to commit"
          git push
